package com.next.newsweb.model;

public class Attentiontag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attentiontag.id
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attentiontag.userid
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attentiontag.attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    private String attentiontag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attentiontag.id
     *
     * @return the value of attentiontag.id
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attentiontag.id
     *
     * @param id the value for attentiontag.id
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attentiontag.userid
     *
     * @return the value of attentiontag.userid
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attentiontag.userid
     *
     * @param userid the value for attentiontag.userid
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attentiontag.attentiontag
     *
     * @return the value of attentiontag.attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    public String getAttentiontag() {
        return attentiontag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attentiontag.attentiontag
     *
     * @param attentiontag the value for attentiontag.attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    public void setAttentiontag(String attentiontag) {
        this.attentiontag = attentiontag == null ? null : attentiontag.trim();
    }
}