package com.next.newsweb.model;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_create
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_modified
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.creator
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.view_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.comment_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.like_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.tag
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_create
     *
     * @return the value of news.gmt_create
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_create
     *
     * @param gmtCreate the value for news.gmt_create
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_modified
     *
     * @return the value of news.gmt_modified
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_modified
     *
     * @param gmtModified the value for news.gmt_modified
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.creator
     *
     * @return the value of news.creator
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.creator
     *
     * @param creator the value for news.creator
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.view_count
     *
     * @return the value of news.view_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.view_count
     *
     * @param viewCount the value for news.view_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.comment_count
     *
     * @return the value of news.comment_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.comment_count
     *
     * @param commentCount the value for news.comment_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.like_count
     *
     * @return the value of news.like_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.like_count
     *
     * @param likeCount the value for news.like_count
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.tag
     *
     * @return the value of news.tag
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.tag
     *
     * @param tag the value for news.tag
     *
     * @mbg.generated Mon Apr 06 20:31:51 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}