server:
  port: 8080

github_client_id: 386633813bc6c2608398
github_client_secret: 077197e081f911ac1acd203c33435df1b95d2823
github_redirect_uri: http://localhost:8080/callback

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsweb?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.next.newsweb.mapper
  mapper-locations: classpath:mapper/*.xml