package com.next.newsweb.mapper;

import com.next.newsweb.model.Attentiontag;
import com.next.newsweb.model.AttentiontagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AttentiontagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    long countByExample(AttentiontagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int deleteByExample(AttentiontagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int insert(Attentiontag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int insertSelective(Attentiontag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    List<Attentiontag> selectByExampleWithRowbounds(AttentiontagExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    List<Attentiontag> selectByExample(AttentiontagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    Attentiontag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") Attentiontag record, @Param("example") AttentiontagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int updateByExample(@Param("record") Attentiontag record, @Param("example") AttentiontagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int updateByPrimaryKeySelective(Attentiontag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attentiontag
     *
     * @mbg.generated Sun May 03 22:47:23 CST 2020
     */
    int updateByPrimaryKey(Attentiontag record);
}